name: Netflix DevSecOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-and-security:
    name: Test + Trivy + SonarCloud
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn requests python-dotenv

      - name: Check Python Syntax
        run: |
          python -m py_compile main.py

      - name: Test Netflix API
        run: |
          python -c "from main import app; print('Netflix API loaded successfully')"

      # -------------------------
      # TRIVY SECURITY SCAN
      # -------------------------

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy Filesystem Scan
        run: |
          trivy fs \
            --scanners vuln,secret \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            .

      # -------------------------
      # SONARCLOUD
      # -------------------------

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Vipul468_Netflix-DevSecOps
            -Dsonar.organization=netflix-devsecops

      - name: CI Success
        run: |
          echo "Netflix DevSecOps CI completed successfully"