- name: SonarCloud Scan
  uses: SonarSource/sonarqube-scan-action@v6
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  with:
    args: >
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.projectKey=Vipul468_Netflix-DevSecOps
      -Dsonar.organization=netflix-devsecops